### ISSUE TITLE
Doesn't populate test data correctly

### ISSUE THREAD

**Issue by andymckay** [jbalogh/jingo#25]
The test suite when it sets up the site monkey patches template rendering so that it sends the right signal that test suite needs. That signal is then caught and populates things like request.context so you can examine them in a test.

However the monkey patch inside django tests, patches the _render method. Jingo doesn't call that. Instead it relies upon the TEMPLATE_DEBUG flag to be set if it is, it calls the signal.

The upshot is, if you don't set TEMPLATE_DEBUG in your tests, request.context ends up as None. Ideally we'd use a _render method in jingo so we can detect when the signal is being added.

**Comment by jsocol** [comment]
@andymckay If this is still an issue, and you can recall what it was, please reopen this, otherwise I'm closing it as part of some old-issue cleanup.

**Comment by andymckay** [comment]
No idea anymore :)
