### ISSUE TITLE
Please release a new version to PyPI

### ISSUE THREAD

**Issue by bobsilverberg** [jbalogh/jingo#64]
There have been some patches added to jingo that are not in version 0.7.
Would it be possible to do a release?

**Comment by peterbe** [comment]
ping @jsocol since I think you can do releases on this project too, right?

**Comment by jsocol** [comment]
Yeah I'm the primary maintainer. I'll take a look this week. Number, I think, #71 still needs to be fixed and has some comments. (A regression in the behavior of |f, whichever PR that is.)

--

**Comment by peterbe** [comment]
Number #71?

**Comment by jsocol** [comment]
Oh and of course it doesn't even link issues when you comment via email. It's #59. Number #59. Number No. #59.

**Comment by mythmon** [comment]
It seems #59 is almost ready to go. With Django 1.8 looming on the horizon, it's becoming more and more important to have a release of Jingo that support Django 1.7 (Before 1.6 is deprecated). Any chance of this getting fixed soon?

**Comment by jsocol** [comment]
Closing this in favor of #67, and the fact that 0.7.1 is out.
