### ISSUE TITLE
Add me to your committers or transfer the app over to Mozilla

### ISSUE THREAD

**Issue by jezdez** [jbalogh/jingo#73]
Jingo continues to be a central part of the Django sites at Mozilla and is currently blocking the upgrade to the current Django LTS release as well as the use of modern Django techniques.

Since there is a history of slow responses from the maintainers I'd like to propose myself as another team member to be able to deliver faster releases that work on current Django releases.

Alternatively (which I would prefer) let's transfer the whole app to the mozilla namespace and spread the workload to the rest of the webdevs/webengs at Mozilla. This is an essential part of the success of our sites and should serve as a reminder that OSS often also means to step up when the original authors are not able to support maintenance in their spare time.

Given Django 1.8's own Jinja2 support I would estimate a big chance to make Jingo a thin wrapper around that feature lowering the maintenance burden even further.

@jbalogh @jsocol Opinions?

**Comment by jsocol** [comment]
I'd support adding @jezdez as a committer. The bigger issue is PyPI releases. Are you also "jezdez" there? Thanks for volunteering!

**Comment by jezdez** [comment]
@jsocol Yep, I am.

**Comment by jbalogh** [comment]
I'm fine transferring it to mozilla. Want me to do that?

**Comment by jsocol** [comment]
@jezdez Added you to the PyPI project as an owner, too.

If y'all feel it's best and there will actually be ownership from the webdev team, I say go for moving it to the moz org. If it's better served by just making Jannis a collab here, that works, too.

**Comment by jezdez** [comment]
@jsocol Yeah, I do feel like it would make things easier, not that I would ask for you to drop your commit privileges, that'd be awful. GitHub nowadays does repo redirects nicely so we don't have to worry about people finding it again.

**Comment by jsocol** [comment]
@jbalogh ^ all you

**Comment by jbalogh** [comment]
I can't transfer directly to mozilla since I'm not an admin. I put in a request to transfer to @jezdez, and you can :arrow_right:  it to mozilla from there.

**Comment by jsocol** [comment]
It sounds like moz webdev is moving away from Jingo to django-jinja pretty fast. I'm not, though, or at least not yet. So @jezdez do you think it still makes sense to move to the Moz org?

**Comment by jezdez** [comment]
@jsocol I think things happened faster than I anticipated and it seems as if we're moving with MDN eventually as well. I think we don't need to move it to Mozilla right now. Thanks for revisiting this issue!
