### ISSUE TITLE
Port to Django 1.9:  ``from django.template.base import TemplateDoesNotExist`` ImportError.

### ISSUE THREAD

**Issue by Natim** [jbalogh/jingo#78]
File "/usr/lib/python2.7/site-packages/jingo/__init__.py", line 11, in <module>
    from django.template.base import Origin, TemplateDoesNotExist
ImportError: cannot import name TemplateDoesNotExist

**Comment by jsocol** [comment]
Honestly, I'd recommend going with [django-jinja](https://pypi.python.org/pypi/django-jinja) for 1.9. The approach Jingo uses is a much older one and I don't know that it's makes sense to maintain going into the 1.9 and up world.
